### PR TITLE
Add missing runtime dependencies (fixes #3)

### LINKED ISSUE #3: [1.1] Missing install_requires=['docutils'] ?
```console
# cd "$(mktemp -d)"

# virtualenv --python=python3.7 py37
Running virtualenv with interpreter /usr/bin/python3.7
Already using interpreter /usr/bin/python3.7
Using base prefix '/usr'
New python3.7 executable in /tmp/tmp.wrF8nD7QPR/py37/bin/python3.7
Not overwriting existing python3.7 script /tmp/tmp.wrF8nD7QPR/py37/bin/python3.7 (you must use /tmp/tmp.wrF8nD7QPR/py37/bin/python3.7)
Installing setuptools, pip, wheel...
done.

# source py37/bin/activate

# pip install sphinxcontrib_github_alt
Collecting sphinxcontrib_github_alt
  Using cached sphinxcontrib_github_alt-1.1-py2.py3-none-any.whl (8.9 kB)
Installing collected packages: sphinxcontrib-github-alt
Successfully installed sphinxcontrib-github-alt-1.1

# python -c 'import sphinxcontrib_github_alt'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/tmp.wrF8nD7QPR/py37/lib/python3.7/site-packages/sphinxcontrib_github_alt.py", line 18, in <module>
    from docutils import nodes, utils
ModuleNotFoundError: No module named 'docutils'
```

### PR DESCRIPTION
**Pull request by hartwork**
Fixes #3

The new GitHub Action can be inspected [over here](https://github.com/hartwork/sphinxcontrib_github_alt/actions).

### CODE REVIEW

**Comment by hartwork** [comment]
What do you think?

**Comment by takluyver** [comment]
Thanks!

**Comment by takluyver** [comment]
Released 1.2.

**Comment by hartwork** [comment]
Thank you!

**Pull request merged**
